name: Tartufo scan push for secrets

on: [ push ]  # Trigger on all pushes to all branches

jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@HEAD

      - name: Checkout GoDaddy Actions Tartufo repo
        uses: actions/checkout@HEAD
        with:
          repository: gdcorp-actions/tartufo
          token: ${{ secrets.GITHUB_TOKEN }} # PAT with read access to gdcorp-actions/tartufo
          ref: v2.1.0
          path: tartufo
          persist-credentials: false # Do not persist auth token in local git config.

      - name: Run Tartufo from gdcorp-actions/tartufo repository
        uses: ./tartufo
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
